# SPDX-FileCopyrightText: 2023 The Template-Sandbox Authors
#
# SPDX-License-Identifier: Apache-2.0

pipeline:
  tests:
    image: python:3.9-slim
    commands:
      - pip install nox==2022.11.21
      - pip install poetry==1.4.1
      - poetry install --all-extras
      - nox
  publish:
    image: python:3.9-slim
    commands:
      - pip install nox==2022.11.21
      - pip install poetry==1.4.1
      - poetry install --all-extras
      - nox
      - poetry build
      - poetry config repositories.testpypi https://test.pypi.org/legacy/
      - poetry publish --username=__token__ --repository testpypi --password=$TEST_PYPI_TOKEN
    secrets: [ test_pypi_token ]
    when:
      tag: release-*
