# SPDX-FileCopyrightText: 2023 The Template-Sandbox Authors
#
# SPDX-License-Identifier: Apache-2.0

pipeline:
  install:
    image: python:3.9-slim
    commands:
      - pip install nox==2022.11.21
      - pip instal poetry==1.4.1
      - poetry install --all-extras
  tests:
    image: python:3.9-slim
    commands:
      - nox
