# SPDX-FileCopyrightText: 2023 The Template-Sandbox Authors
#
# SPDX-License-Identifier: Apache-2.0

pipeline:
  tests:
    image: python:3.11-slim
    commands:
      - pip install nox==2023.4.22
      - pip install poetry==1.5.1
      - poetry install --all-extras
      - nox
  publish:
    image: python:3.11-slim
    commands:
      - pip install nox==2023.4.22
      - pip install poetry==1.5.1
      - poetry install --all-extras
      - nox
      - poetry build
      - poetry config repositories.testpypi https://test.pypi.org/legacy/
      - poetry publish --username=__token__ --repository testpypi --password=$TEST_PYPI_TOKEN
    secrets: [ test_pypi_token ]
    when:
      event: tag
      tag: v*
