# SPDX-FileCopyrightText: 2023 The Template-Sandbox Authors
#
# SPDX-License-Identifier: Apache-2.0

name: temp-sand
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - mamba
  - pip
  - poetry
  - conda-lock

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
